baseURL = "http://lpub.org/"
languageCode = "en-us"
title = "Libertas Publica"
theme = "hugo-blox" # theme = "papermod"

[params]
description = "Open Information with Open Minds"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Documents"
url = "/documents/"
weight = 3
